#!/bin/bash
### BEGIN INIT INFO
# Provides:          iDronDataAnalyzer
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description:
#
### END INIT INFO

#DEMONIO

cd /usr/local/bin/iDronDataAnalyzer

case "$1" in
  start)
    echo "Iniciando iDronDataAnalyzer..."
    ./run.sh
  ;;
  stop)
    echo "Apagando iDronDataAnalyzer..."
    ./destroy.sh
  ;;
  restart)
	echo "Reiniciando iDronDataAnalyzer..."
	./destroy.sh
	./run.sh
  ;;
  *)
    echo "Uso: $0 {start|stop|restart}"
    exit 1
esac

exit 0
